/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aram;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashad Nadeem
 */
public class PatientGUI extends javax.swing.JFrame{


    /**
     * Creates new form Questions
     */
    public PatientGUI() throws FileNotFoundException,NullPointerException{
        
        entry = new Patient();
        file = new RandomAccessFile("PersonalData.dat","rw");
        gen = ' ';
        initComponents();
        this.setVisible(true);
        this.setAlwaysOnTop(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        autenticateL = new javax.swing.JLabel();
        NameL = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        cnicL = new javax.swing.JLabel();
        cnicTF = new javax.swing.JTextField();
        ageL = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();
        bgL = new javax.swing.JLabel();
        bgCB = new javax.swing.JComboBox<>();
        genderL = new javax.swing.JLabel();
        maleRB = new javax.swing.JRadioButton();
        femaleRB = new javax.swing.JRadioButton();
        otherRB = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        edoctorJB = new javax.swing.JButton();
        dictionaryJB = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        submitJB = new javax.swing.JButton();
        alreadyRegJB = new javax.swing.JButton();
        exitJB = new javax.swing.JButton();
        adminL = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Questions - ARAMcrop");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(390, 520));
        getContentPane().setLayout(null);

        autenticateL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        autenticateL.setForeground(new java.awt.Color(255, 0, 0));
        autenticateL.setText("Authentication Required");
        autenticateL.setVisible(false);
        getContentPane().add(autenticateL);
        autenticateL.setBounds(210, 445, 140, 20);

        NameL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NameL.setForeground(new java.awt.Color(0, 0, 153));
        NameL.setText("Name:");
        getContentPane().add(NameL);
        NameL.setBounds(12, 64, 49, 34);

        NameTF.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        NameTF.setForeground(Color.lightGray);
        NameTF.setText("Someone");
        NameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameTFFocusLost(evt);
            }
        });
        getContentPane().add(NameTF);
        NameTF.setBounds(77, 65, 194, 34);

        cnicL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cnicL.setForeground(new java.awt.Color(0, 0, 153));
        cnicL.setText("Cnic No:");
        getContentPane().add(cnicL);
        cnicL.setBounds(12, 117, 58, 34);

        cnicTF.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        cnicTF.setForeground(Color.LIGHT_GRAY);
        cnicTF.setText("4230123456789");
        cnicTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnicTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnicTFFocusLost(evt);
            }
        });
        getContentPane().add(cnicTF);
        cnicTF.setBounds(77, 118, 194, 34);

        ageL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ageL.setForeground(new java.awt.Color(0, 0, 153));
        ageL.setText("Age:");
        getContentPane().add(ageL);
        ageL.setBounds(12, 170, 58, 34);

        ageTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(ageTF);
        ageTF.setBounds(77, 171, 50, 34);

        bgL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bgL.setForeground(new java.awt.Color(0, 0, 153));
        bgL.setText("Blood-Group:");
        getContentPane().add(bgL);
        bgL.setBounds(12, 218, 94, 34);

        bgCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bgCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+ ", "A- ", "B+ ", "B- ", "AB+", "AB-", "O+ ", "O- " }));
        bgCB.setAutoscrolls(true);
        bgCB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(bgCB);
        bgCB.setBounds(111, 224, 70, 23);

        genderL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderL.setForeground(new java.awt.Color(0, 0, 153));
        genderL.setText("Gender:");
        getContentPane().add(genderL);
        genderL.setBounds(12, 270, 62, 34);

        buttonGroup1.add(maleRB);
        maleRB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        maleRB.setText("Male");
        maleRB.setOpaque(false);
        maleRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                maleRBItemStateChanged(evt);
            }
        });
        getContentPane().add(maleRB);
        maleRB.setBounds(82, 276, 60, 23);

        buttonGroup1.add(femaleRB);
        femaleRB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        femaleRB.setText("Female");
        femaleRB.setOpaque(false);
        femaleRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                femaleRBItemStateChanged(evt);
            }
        });
        getContentPane().add(femaleRB);
        femaleRB.setBounds(147, 276, 80, 23);

        buttonGroup1.add(otherRB);
        otherRB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        otherRB.setText("Other");
        otherRB.setOpaque(false);
        otherRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                otherRBItemStateChanged(evt);
            }
        });
        getContentPane().add(otherRB);
        otherRB.setBounds(228, 276, 70, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(12, 311, 336, 10);

        edoctorJB.setBackground(new java.awt.Color(0, 102, 51));
        edoctorJB.setForeground(new java.awt.Color(255, 255, 255));
        edoctorJB.setText("E-Doctor");
        edoctorJB.setSelected(true);
        edoctorJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edoctorJBActionPerformed(evt);
            }
        });
        getContentPane().add(edoctorJB);
        edoctorJB.setBounds(218, 322, 100, 36);

        dictionaryJB.setBackground(new java.awt.Color(0, 153, 153));
        dictionaryJB.setForeground(new java.awt.Color(255, 255, 255));
        dictionaryJB.setText("Medical Data Base");
        dictionaryJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dictionaryJBActionPerformed(evt);
            }
        });
        getContentPane().add(dictionaryJB);
        dictionaryJB.setBounds(35, 322, 150, 36);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(12, 365, 353, 10);

        submitJB.setBackground(new java.awt.Color(153, 0, 153));
        submitJB.setForeground(new java.awt.Color(255, 255, 255));
        submitJB.setText("Submit");
        submitJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJBActionPerformed(evt);
            }
        });
        getContentPane().add(submitJB);
        submitJB.setBounds(12, 378, 88, 36);

        alreadyRegJB.setBackground(new java.awt.Color(153, 0, 0));
        alreadyRegJB.setForeground(new java.awt.Color(255, 255, 255));
        alreadyRegJB.setText("Already Registered");
        alreadyRegJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alreadyRegJBActionPerformed(evt);
            }
        });
        getContentPane().add(alreadyRegJB);
        alreadyRegJB.setBounds(118, 378, 160, 36);

        exitJB.setBackground(new java.awt.Color(255, 102, 102));
        exitJB.setText("Exit");
        exitJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJBActionPerformed(evt);
            }
        });
        getContentPane().add(exitJB);
        exitJB.setBounds(295, 378, 60, 36);

        adminL.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        adminL.setForeground(new java.awt.Color(102, 102, 255));
        adminL.setText("Admin Panel");
        adminL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminLMouseExited(evt);
            }
        });
        getContentPane().add(adminL);
        adminL.setBounds(277, 427, 88, 15);

        jTextField1.setMinimumSize(new java.awt.Dimension(1, 2));
        jTextField1.setName(""); // NOI18N
        jTextField1.setOpaque(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(2, 2));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(66, 64, 4, 2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/M3.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 370, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameTFFocusGained
        // TODO add your handling code here:
        if(NameTF.getText().equals("Someone")){
            NameTF.setText("");
            NameTF.setForeground(null);
        }
    }//GEN-LAST:event_NameTFFocusGained

    private void NameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameTFFocusLost
        // TODO add your handling code here:
        if(NameTF.getText().equals("")){
            NameTF.setForeground(Color.LIGHT_GRAY);
            NameTF.setText("Someone");
        }
    }//GEN-LAST:event_NameTFFocusLost

    private void cnicTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicTFFocusGained
        // TODO add your handling code here:
        if(cnicTF.getText().equals("4230123456789")){
            cnicTF.setText("");
            cnicTF.setForeground(null);
        }
    }//GEN-LAST:event_cnicTFFocusGained

    private void cnicTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicTFFocusLost
        // TODO add your handling code here:
        if(cnicTF.getText().equals("")){
            cnicTF.setForeground(Color.LIGHT_GRAY);
            cnicTF.setText("4230123456789");
        }
    }//GEN-LAST:event_cnicTFFocusLost

    private void maleRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_maleRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == maleRB) gen = 'M';
    }//GEN-LAST:event_maleRBItemStateChanged

    private void femaleRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_femaleRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == femaleRB) gen = 'F';
    }//GEN-LAST:event_femaleRBItemStateChanged

    private void otherRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_otherRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == otherRB) gen = 'O';
    }//GEN-LAST:event_otherRBItemStateChanged

    private void edoctorJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edoctorJBActionPerformed
        try {
            // TODO add your handling code here:
            Questions q = new Questions(entry);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PatientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null,"Please Submit Your Details First", "Error!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_edoctorJBActionPerformed

    private void dictionaryJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dictionaryJBActionPerformed
        try {
            // TODO add your handling code here:
            DictionaryGUI d = new DictionaryGUI();
            d.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PatientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dictionaryJBActionPerformed

    private void submitJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJBActionPerformed
        // TODO add your handling code here:
        try{
            String bg = (String)bgCB.getSelectedItem();
            if(bg == null) bg = "";
            System.out.println(bg);
            entry.setValues(NameTF.getText(),cnicTF.getText(),ageTF.getText(),gen,bg);
            edoctorJB.setBackground(Color.GREEN);
            int save = JOptionPane.showConfirmDialog(null, "Do You Want to Save Your Details?","Save Changes",JOptionPane.YES_NO_OPTION);
            if (save == 0){
                //entry.write();
                entry.write(file);
                JOptionPane.showMessageDialog(null,"Entry Added! " + entry.getName(), "Saved!", JOptionPane.INFORMATION_MESSAGE);
            }
            else  {}
            fillinfo();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PatientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PatientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Blank E){
            JOptionPane.showMessageDialog(null,E.toString(), "Error!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_submitJBActionPerformed

    private void alreadyRegJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alreadyRegJBActionPerformed
        // TODO add your handling code here:
        try {
            String searchText = JOptionPane.showInputDialog(null, "SEARCH BY Name or Cnic","");
            Patient a = new Patient();
            entry = a.alreadyRegistered(searchText);
            JOptionPane.showMessageDialog(null,("Record Found, you can now use E-Doctor " + entry.getName().trim()), "User Found!", JOptionPane.INFORMATION_MESSAGE);
            fillinfo();
            edoctorJB.setBackground(Color.GREEN);
        } catch (IOException ex) {
            Logger.getLogger(PatientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Blank ex) {
            JOptionPane.showMessageDialog(null,ex.toString(), "Error!", JOptionPane.WARNING_MESSAGE);
            this.setVisible(false);
            try {
                PatientGUI p = new PatientGUI();
            } catch (FileNotFoundException ex1) {
                Logger.getLogger(PatientGUI.class.getName()).log(Level.SEVERE, null, ex1);
            } catch (NullPointerException ex1) {
                Logger.getLogger(PatientGUI.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_alreadyRegJBActionPerformed

    private void exitJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJBActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null,"Are you sure you want to exit?", "Exit", JOptionPane.OK_CANCEL_OPTION);
        if (exit == 0) System.exit(0);
    }//GEN-LAST:event_exitJBActionPerformed

    private void adminLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLMouseClicked
        // TODO add your handling code here:
        System.err.print("Admin");
        try {
            Login lg = new Login();
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null," Admin File Not Found ", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_adminLMouseClicked

    private void adminLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLMouseEntered
        // TODO add your handling code here:
        autenticateL.setVisible(true);
    }//GEN-LAST:event_adminLMouseEntered

    private void adminLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLMouseExited
        // TODO add your handling code here:
        autenticateL.setVisible(false);
    }//GEN-LAST:event_adminLMouseExited
    
    private void fillinfo(){
        NameTF.setForeground(null);
        cnicTF.setForeground(null);
        
        NameTF.setEditable(false);
        cnicTF.setEditable(false);
        ageTF.setEditable(false);
        bgCB.setEditable(false);
        
        NameTF.setText(entry.getName().trim());
        ageTF.setText(""+entry.getAge());
        cnicTF.setText(entry.getCnic().trim());
        bgCB.setSelectedItem(entry.getBG());
        buttonGroup1.clearSelection();
        if(entry.getGender() == 'M') maleRB.setSelected(true);
        if(entry.getGender() == 'F') femaleRB.setSelected(true);
        if(entry.getGender() == 'O') otherRB.setSelected(true);
    }
    
    private Patient entry;
    private RandomAccessFile file;
    private char gen;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JLabel adminL;
    private javax.swing.JLabel ageL;
    private javax.swing.JTextField ageTF;
    private javax.swing.JButton alreadyRegJB;
    private javax.swing.JLabel autenticateL;
    private javax.swing.JComboBox<String> bgCB;
    private javax.swing.JLabel bgL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cnicL;
    private javax.swing.JTextField cnicTF;
    private javax.swing.JButton dictionaryJB;
    private javax.swing.JButton edoctorJB;
    private javax.swing.JButton exitJB;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JLabel genderL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JRadioButton otherRB;
    private javax.swing.JButton submitJB;
    // End of variables declaration//GEN-END:variables
}
