/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aram;

import aram.DictionaryGUI;
import aram.DictionaryGUI;
import aram.DictionaryGUI;
import aram.Patient;
import aram.Patient;
import aram.Patient;
import aram.PatientGUI;
import aram.PatientGUI;
import aram.PatientGUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Abdur-Rafay
 */
public class ResultGUI extends javax.swing.JFrame {

    private Patient patient;
    
    public ResultGUI(Patient patient) throws InterruptedException {
        
        this.patient = patient;
        initComponents();
        this.setSize(765, 830);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        MandatoryPaint();
        ResultPanel.setVisible(false);
        Gifpanel.setVisible(true);
        Thread th = Thread.currentThread();
        delay(10);
        //System.exit(0);
        //Gifpanel.setVisible(false);
        //ResultPanel.setVisible(true);
        
    }
    public void delay(int d){
        // delay of one second here
        timer = new Timer(0, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent evt) { 
            //System.exit(0); //repaint the gui, or you want see the effect
            afterDelay();
            
        }
        });
        timer.setInitialDelay(d * 1000); //wait one second
        timer.setRepeats(false); //only once
        timer.start();
    }
    public void afterDelay(){
        Gifpanel.setVisible(false);
        ResultPanel.setVisible(true);
        if (this.patient.getDisease().isEmpty())
            OptionalPaint2();
        else
            OptionalPaint1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        AgeField = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        GenderTextField = new javax.swing.JTextField();
        BGLabel = new javax.swing.JLabel();
        BGTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CNICTextField = new javax.swing.JTextField();
        PersonalInfoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ResultLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Gifpanel = new javax.swing.JLabel();
        ResultPanel = new javax.swing.JPanel();
        ProcessResultIcon = new javax.swing.JLabel();
        DiseaseTextField1 = new javax.swing.JTextField();
        DiseaseTextField2 = new javax.swing.JTextField();
        DiseaseTextField3 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("YOUR RESULTS ARE HERE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 290, 40);

        NameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        NameLabel.setText("Name:");
        getContentPane().add(NameLabel);
        NameLabel.setBounds(50, 110, 78, 43);

        NameField.setEditable(false);
        NameField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 18)); // NOI18N
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NameField);
        NameField.setBounds(140, 110, 414, 43);

        AgeLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AgeLabel.setText("Age:");
        getContentPane().add(AgeLabel);
        AgeLabel.setBounds(50, 190, 58, 43);

        AgeField.setEditable(false);
        AgeField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 18)); // NOI18N
        AgeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(AgeField);
        AgeField.setBounds(140, 190, 128, 43);

        GenderLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        GenderLabel.setText("Gender:");
        getContentPane().add(GenderLabel);
        GenderLabel.setBounds(50, 280, 72, 35);

        GenderTextField.setEditable(false);
        GenderTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 18)); // NOI18N
        GenderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(GenderTextField);
        GenderTextField.setBounds(140, 270, 128, 42);

        BGLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BGLabel.setText("Blood Group:");
        getContentPane().add(BGLabel);
        BGLabel.setBounds(380, 190, 117, 44);

        BGTextField.setEditable(false);
        BGTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 18)); // NOI18N
        BGTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(BGTextField);
        BGTextField.setBounds(510, 190, 128, 45);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("            CNIC:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 280, 117, 22);

        CNICTextField.setEditable(false);
        CNICTextField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 18)); // NOI18N
        CNICTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNICTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(CNICTextField);
        CNICTextField.setBounds(510, 270, 206, 46);

        PersonalInfoLabel.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        PersonalInfoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/job.png"))); // NOI18N
        PersonalInfoLabel.setText("YOUR PERSONAL INFORMATION");
        getContentPane().add(PersonalInfoLabel);
        PersonalInfoLabel.setBounds(50, 70, 383, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/iconfinder_Problem_131793.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(219, 13, 32, 45);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/iconfinder_Problem_131793.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(544, 13, 32, 38);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/iconfinder_Problem_131793.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 13, 32, 45);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/iconfinder_Problem_131793.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(505, 13, 32, 38);

        ResultLabel.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        ResultLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/iconfinder_Search_131849.png"))); // NOI18N
        ResultLabel.setText("YOUR E-DOCTOR RESULT");
        getContentPane().add(ResultLabel);
        ResultLabel.setBounds(50, 330, 372, 32);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/iconfinder_Home_131778.png"))); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 730, 157, 59);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/iconfinder_List_131880.png"))); // NOI18N
        jButton2.setText("Medical Database");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(457, 730, 240, 59);

        Gifpanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/Loading.gif"))); // NOI18N
        getContentPane().add(Gifpanel);
        Gifpanel.setBounds(200, 370, 400, 330);

        DiseaseTextField1.setEditable(false);
        DiseaseTextField1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        DiseaseTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiseaseTextField1ActionPerformed(evt);
            }
        });

        DiseaseTextField2.setEditable(false);
        DiseaseTextField2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        DiseaseTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiseaseTextField2ActionPerformed(evt);
            }
        });

        DiseaseTextField3.setEditable(false);
        DiseaseTextField3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        DiseaseTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DiseaseTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiseaseTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResultPanelLayout = new javax.swing.GroupLayout(ResultPanel);
        ResultPanel.setLayout(ResultPanelLayout);
        ResultPanelLayout.setHorizontalGroup(
            ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanelLayout.createSequentialGroup()
                .addGroup(ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResultPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ProcessResultIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultPanelLayout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DiseaseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiseaseTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DiseaseTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        ResultPanelLayout.setVerticalGroup(
            ResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ProcessResultIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DiseaseTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DiseaseTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DiseaseTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(ResultPanel);
        ResultPanel.setBounds(20, 370, 720, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
          
    }//GEN-LAST:event_NameFieldActionPerformed

    private void AgeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeFieldActionPerformed
           
    }//GEN-LAST:event_AgeFieldActionPerformed

    private void GenderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderTextFieldActionPerformed
       
    }//GEN-LAST:event_GenderTextFieldActionPerformed

    private void BGTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGTextFieldActionPerformed
         
    }//GEN-LAST:event_BGTextFieldActionPerformed

    private void CNICTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNICTextFieldActionPerformed
           
    }//GEN-LAST:event_CNICTextFieldActionPerformed

    private void DiseaseTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiseaseTextField1ActionPerformed
          
    }//GEN-LAST:event_DiseaseTextField1ActionPerformed

    private void DiseaseTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiseaseTextField2ActionPerformed
           
    }//GEN-LAST:event_DiseaseTextField2ActionPerformed

    private void DiseaseTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiseaseTextField3ActionPerformed
           
    }//GEN-LAST:event_DiseaseTextField3ActionPerformed
    private void MandatoryPaint(){
         NameField.setText(patient.getName().trim());
         AgeField.setText(String.valueOf(patient.getAge()).trim());
         GenderTextField.setText(String.valueOf(patient.getGender()).trim());
         BGTextField.setText(String.valueOf(patient.getBG()).trim());
         CNICTextField.setText(String.valueOf(patient.getCnic()).trim());   
         
    }
    
    private void OptionalPaint1(){
        ProcessResultIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/2ca6a3e17801debdd20a67a016846711_stamp-with-word-success-inside-vector-illustration-royalty-free-_1300-725.jpeg")));
        DiseaseTextField1.setText("Our Artificial Intelligence program has successfully figured out your disease");
        DiseaseTextField2.setText("According to the questions you answered, it appears that you have the following disease:");
        DiseaseTextField3.setText(patient.getDisease().toUpperCase().trim()); 
    }
    
    private void OptionalPaint2(){
        ProcessResultIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aram/failed-stamp-png-3.png")));
        DiseaseTextField1.setText("We are sorry for the inconvenience but our system could not figure out your disease");
        DiseaseTextField2.setText("The answers you provided weren't enough for us point out a certain disease");
        DiseaseTextField3.setText("Please visit the Medical Databse for further information"); 
    }
    
    protected void threading() throws InterruptedException{
        Thread.sleep(5000);
        Gifpanel.setVisible(false);
        ResultPanel.setVisible(true);
        if (this.patient.getDisease().isEmpty())
            OptionalPaint2();
        else
            OptionalPaint1();
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            DictionaryGUI Instance = new DictionaryGUI();
            Instance.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ResultGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            PatientGUI pat = new PatientGUI();
            pat.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ResultGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            Logger.getLogger(ResultGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
               // Patient patient = new Patient();
                //new ResultGUI(patient).setVisible(true);
            }
        //});
   // }
    private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeField;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel BGLabel;
    private javax.swing.JTextField BGTextField;
    private javax.swing.JTextField CNICTextField;
    private javax.swing.JTextField DiseaseTextField1;
    private javax.swing.JTextField DiseaseTextField2;
    private javax.swing.JTextField DiseaseTextField3;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JTextField GenderTextField;
    private javax.swing.JLabel Gifpanel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel PersonalInfoLabel;
    private javax.swing.JLabel ProcessResultIcon;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JPanel ResultPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
