package aram;


import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class UpdateCredentialsGUI extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCredentials
     */
    public UpdateCredentialsGUI() throws FileNotFoundException {
        admin = new Admin();
        file = new RandomAccessFile("AdminData.dat","rw");
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Exit = new javax.swing.JButton();
        addRB = new javax.swing.JRadioButton();
        emoveRB = new javax.swing.JRadioButton();
        updateRB = new javax.swing.JRadioButton();
        MenuL = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AddPanel = new javax.swing.JPanel();
        genderL = new javax.swing.JLabel();
        maleRB = new javax.swing.JRadioButton();
        femaleRB = new javax.swing.JRadioButton();
        otherRB = new javax.swing.JRadioButton();
        addJB = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addidTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addPswTF = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        NameL = new javax.swing.JLabel();
        addPsw2 = new javax.swing.JPasswordField();
        NameTF = new javax.swing.JTextField();
        cnicL = new javax.swing.JLabel();
        cnicTF = new javax.swing.JTextField();
        ageL = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();
        removePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        removeidTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        removePswTF = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        removeJB = new javax.swing.JButton();
        updatePanel = new javax.swing.JPanel();
        IDTF = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        oldPswTF = new javax.swing.JPasswordField();
        newPswTF = new javax.swing.JPasswordField();
        newPsw2TF = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Credential");

        Exit.setBackground(new java.awt.Color(255, 102, 102));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        buttonGroup2.add(addRB);
        addRB.setText("Add Admin");
        addRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addRBItemStateChanged(evt);
            }
        });

        buttonGroup2.add(emoveRB);
        emoveRB.setText("Remove Admin");
        emoveRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                emoveRBItemStateChanged(evt);
            }
        });

        buttonGroup2.add(updateRB);
        updateRB.setText("Update Credentials");
        updateRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateRBItemStateChanged(evt);
            }
        });

        MenuL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MenuL.setText("Menu:");

        genderL.setText("Gender:");

        buttonGroup1.add(maleRB);
        maleRB.setText("Male");
        maleRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                maleRBItemStateChanged(evt);
            }
        });

        buttonGroup1.add(femaleRB);
        femaleRB.setText("Female");
        femaleRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                femaleRBItemStateChanged(evt);
            }
        });

        buttonGroup1.add(otherRB);
        otherRB.setText("Other");
        otherRB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                otherRBItemStateChanged(evt);
            }
        });

        addJB.setText("Add");
        addJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJBActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel12.setText("Add Admin");

        jLabel4.setText("User ID :");

        addidTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addidTFActionPerformed(evt);
            }
        });

        jLabel7.setText("Password :");

        jLabel8.setText("Confirm Password :");

        NameL.setText("Name:");

        NameTF.setForeground(Color.lightGray);
        NameTF.setText("Someone");
        NameTF.setPreferredSize(new java.awt.Dimension(6, 20));
        NameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameTFFocusLost(evt);
            }
        });

        cnicL.setText("Cnic No:");

        cnicTF.setForeground(Color.LIGHT_GRAY);
        cnicTF.setText("4230123456789");
        cnicTF.setPreferredSize(new java.awt.Dimension(6, 20));
        cnicTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnicTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnicTFFocusLost(evt);
            }
        });

        ageL.setText("Age:");

        javax.swing.GroupLayout AddPanelLayout = new javax.swing.GroupLayout(AddPanel);
        AddPanel.setLayout(AddPanelLayout);
        AddPanelLayout.setHorizontalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cnicL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnicTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(ageL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddPanelLayout.createSequentialGroup()
                                .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120))
                            .addComponent(addPswTF)
                            .addComponent(addPsw2)
                            .addComponent(addidTF)))
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(addJB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddPanelLayout.createSequentialGroup()
                                .addComponent(genderL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maleRB)
                                .addGap(10, 10, 10)
                                .addComponent(femaleRB)
                                .addGap(10, 10, 10)
                                .addComponent(otherRB))
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AddPanelLayout.setVerticalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameL)
                    .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnicL)
                    .addComponent(cnicTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ageL)
                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderL)
                    .addComponent(maleRB)
                    .addComponent(femaleRB)
                    .addComponent(otherRB))
                .addGap(5, 5, 5)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addPswTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addPsw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addJB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Admin", AddPanel);

        jLabel10.setText("User ID :");

        removeidTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeidTFActionPerformed(evt);
            }
        });

        jLabel11.setText("Password :");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Remove Admin");

        removeJB.setText("Remove");
        removeJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removePanelLayout = new javax.swing.GroupLayout(removePanel);
        removePanel.setLayout(removePanelLayout);
        removePanelLayout.setHorizontalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(removeJB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(removePanelLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removePswTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removePanelLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeidTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        removePanelLayout.setVerticalGroup(
            removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(removeidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(removePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(removePswTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeJB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remove Admin", removePanel);

        IDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTFActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("User ID :");

        jLabel3.setText("Old Password :");

        jLabel5.setText("New Password :");

        jLabel6.setText("Confirm Password :");

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setText("Update Credentials");

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(oldPswTF, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(newPswTF)
                            .addComponent(newPsw2TF)
                            .addComponent(updateButton)
                            .addComponent(IDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addGap(20, 20, 20))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(IDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oldPswTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(newPswTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newPsw2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update Credentials", updatePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MenuL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addRB)
                            .addComponent(updateRB)
                            .addComponent(emoveRB))
                        .addGap(0, 132, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuL)
                    .addComponent(emoveRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateRB)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTFActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            long ptr = admin.searchString(file,IDTF.getText().trim(),admin.SearchTA);
            file.seek(ptr);
            admin.read(file);
            if(admin.getUserPsw().trim().equals(oldPswTF.getText().trim())){
                if(newPswTF.getText().equals(newPsw2TF.getText()))
                {   
                    admin.setuserpass(IDTF.getText().trim(), newPswTF.getText().trim());
                    admin.updateCredentials(file);
                    JOptionPane.showMessageDialog(this, "New credentials updated successfully");
                    this.setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Password and Confirm Password did not matched. Try Again.");
                }
            } else throw new Blank("Invalid Login");
            
        } catch (FileNotFoundException ex) {
            //Logger.getLogger(UpdateCredentials.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            //Logger.getLogger(UpdateCredentials.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Blank ex) {
            JOptionPane.showMessageDialog(null,ex.toString(), "Update Unsuccessfull", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void NameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameTFFocusGained
        // TODO add your handling code here:
        if(NameTF.getText().equals("Someone")){
            NameTF.setText("");
            NameTF.setForeground(null);
        }
    }//GEN-LAST:event_NameTFFocusGained

    private void NameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameTFFocusLost
        // TODO add your handling code here:
        if(NameTF.getText().equals("")){
            NameTF.setForeground(Color.LIGHT_GRAY);
            NameTF.setText("Someone");
        }
    }//GEN-LAST:event_NameTFFocusLost

    private void cnicTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicTFFocusGained
        // TODO add your handling code here:
        if(cnicTF.getText().equals("4230123456789")){
            cnicTF.setText("");
            cnicTF.setForeground(null);
        }
    }//GEN-LAST:event_cnicTFFocusGained

    private void cnicTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicTFFocusLost
        // TODO add your handling code here:
        if(cnicTF.getText().equals("")){
            cnicTF.setForeground(Color.LIGHT_GRAY);
            cnicTF.setText("4230123456789");
        }
    }//GEN-LAST:event_cnicTFFocusLost

    private void maleRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_maleRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == maleRB) gen = 'M';
    }//GEN-LAST:event_maleRBItemStateChanged

    private void femaleRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_femaleRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == femaleRB) gen = 'F';
    }//GEN-LAST:event_femaleRBItemStateChanged

    private void otherRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_otherRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == otherRB) gen = 'O';
    }//GEN-LAST:event_otherRBItemStateChanged

    private void addJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJBActionPerformed
        // TODO add your handling code here:
        try{
            if(! addPswTF.getText().trim().equals(addPsw2.getText().trim())) throw new Blank("Password and Confirm Password did not matched. Try Again.");
            admin.setValues(NameTF.getText().trim(), ageTF.getText().trim(), addidTF.getText().trim(), addPswTF.getText().trim(), cnicTF.getText().trim(), gen);
            
            admin.write(file);
            JOptionPane.showMessageDialog(null,"Admin Added! " + admin.getName(), "Saved!", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PatientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PatientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Blank E){
            JOptionPane.showMessageDialog(null,E.toString(), "Error!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addJBActionPerformed

    private void addidTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addidTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addidTFActionPerformed

    private void removeidTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeidTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeidTFActionPerformed

    private void removeJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJBActionPerformed
        // TODO add your handling code here:
        try {
            long ptr = admin.searchString(file,removeidTF.getText().trim(),admin.SearchTA);
            file.seek(ptr);
            admin.read(file);
            if(admin.getUserPsw().trim().equals(removePswTF.getText().trim())){
            int remove = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this Admin?","Delete Admin?",JOptionPane.YES_NO_OPTION);
            if (remove == 0){
                admin.removeAdmin(file,removeidTF.getText().trim());
                JOptionPane.showMessageDialog(this, "Admin Deleted successfully");
                this.setVisible(false);
            }
            } else throw new Blank("Invalid Login");
            
        } catch (FileNotFoundException ex) {
            //Logger.getLogger(UpdateCredentials.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            //Logger.getLogger(UpdateCredentials.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Blank ex) {
            JOptionPane.showMessageDialog(null,ex.toString(), "Update Unsuccessfull", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_removeJBActionPerformed

    private void addRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == addRB) menu = 'A';
        paint();
    }//GEN-LAST:event_addRBItemStateChanged

    private void emoveRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_emoveRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == emoveRB) menu = 'R';
        paint();
    }//GEN-LAST:event_emoveRBItemStateChanged

    private void updateRBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_updateRBItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource() == updateRB) menu = 'U';
        paint();
    }//GEN-LAST:event_updateRBItemStateChanged

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ExitActionPerformed
    public void paint(){
        switch(menu){
            case 'A' : jTabbedPane1.setSelectedIndex(0);break;
            case 'R' : jTabbedPane1.setSelectedIndex(1);break;
            case 'U' : jTabbedPane1.setSelectedIndex(2);break;
        }
    }
    /**
     * @param args the command line arguments
     */
    
    private char gen, menu;
    private RandomAccessFile file;
    private Admin admin;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPanel;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField IDTF;
    private javax.swing.JLabel MenuL;
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton addJB;
    private javax.swing.JPasswordField addPsw2;
    private javax.swing.JPasswordField addPswTF;
    private javax.swing.JRadioButton addRB;
    private javax.swing.JTextField addidTF;
    private javax.swing.JLabel ageL;
    private javax.swing.JTextField ageTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cnicL;
    private javax.swing.JTextField cnicTF;
    private javax.swing.JRadioButton emoveRB;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JLabel genderL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JPasswordField newPsw2TF;
    private javax.swing.JPasswordField newPswTF;
    private javax.swing.JPasswordField oldPswTF;
    private javax.swing.JRadioButton otherRB;
    private javax.swing.JButton removeJB;
    private javax.swing.JPanel removePanel;
    private javax.swing.JPasswordField removePswTF;
    private javax.swing.JTextField removeidTF;
    private javax.swing.JButton updateButton;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JRadioButton updateRB;
    // End of variables declaration//GEN-END:variables
}
